name: testsnap-d-sendrecv
base: core22
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap-to-snap IPC testing. send and recv.
description: |
  snap-to-snap IPC testing. send and recv.

grade: stable
#grade: devel # must be 'stable' to release into candidate/stable channels

confinement: strict
#confinement: devmode # use 'strict' once you have the right plugs and slots

# 実行環境のアーキテクチャ UbuntuCore22はx86_64
# "arm64", "armhf", "amd64", "ppc64el", "s390x" 複数指定する場合は[,]で囲う
architectures:
  - amd64

slots:
  # UNIXソケットの共有(recv)
  slot-ipc-dir-testsnap-d:
    interface: content
    content: socket-directoryD
    write: 
      - $SNAP_DATA/export

plugs:
  # UNIXソケットの共有(send)
  plug-ipc-dir-testsnap-d:
    interface: content
    content: socket-directoryC
    target: $SNAP_DATA/import


# 実行コマンドの設定
apps:
  send:
    command: D_client_unix_dgram.py
    plugs:
      - network
      - plug-ipc-dir-testsnap-d

  recv:
    command: D_server_unix_dgram.py
    plugs:
      - network
      - network-bind

# パッケージに取り込むパーツの設定
parts:
  application:
    source: application
    plugin: dump

